### PR TITLE
Fix: The upcast code was assuming that the editor uses a HTMLDataProc…

### LINKED ISSUE #5977: Code block: doesn't work with the markdown data processor
## 📝 Provide detailed reproduction steps (if any)

1.  Create an editor that uses the markdown data processor.
2.  That editor will not properly load code blocks existing in markdown data and an error is thrown.

### PR DESCRIPTION
**Pull request by fredck**
…essor, which is not always true.

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: code blocks upcasting throws when using the markdown DP. Closes [ckeditor/ckeditor5#5977](https://github.com/ckeditor/ckeditor5/issues/5977).

### CODE REVIEW

**Comment by fredck** [comment]
This PR depends on ckeditor/ckeditor5-core#205, therefore the CI failure.

**Comment by Reinmar** [comment]
R+ for most of the changes. But I'm unsure about the changes in ckeditor5-core.

**Comment by fredck** [comment]
> This PR depends on [ckeditor/ckeditor5-core#205](https://github.com/ckeditor/ckeditor5-core/pull/205), therefore the CI failure.

This dependency has been removed. All green now.

**Comment by fredck** [comment]
> R+ for most of the changes. But I'm unsure about the changes in ckeditor5-core.

Just to be clear, the previous commit made it not necessary to touch core anymore.

**Comment by fredck** [comment]
Force-pushed a rebase over v17.0.0.

**Comment by fredck** [comment]
Force-pushed a rebase over v18.0.0.

**Comment by fredck** [comment]
Force-pushed a rebase over v19.0.0.

**Comment by fredck** [comment]
Moved to ckeditor/ckeditor5#7297.

**Pull request closed without merging**
