### PR TITLE
i/5747: Add gifs showcasing tips and tricks

### PR DESCRIPTION
**Pull request by panr**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Docs: Added gifs showcasing tips & tricks. Closes https://github.com/ckeditor/ckeditor5/issues/5747.

### CODE REVIEW

**Comment by Reinmar** [comment]
When trying to build this documentation I got:

```
(master 7b42330) p@m ~/Workspace/ckeditor5> yarn docs --skip-api --snippets=code-blocks
yarn run v1.19.0
$ node --max-old-space-size=4096 ./scripts/docs/build-docs.js --skip-api --snippets=code-blocks
Clean build directory.
Emptying Hexo source directory.
Building documentation failed: undefined
(node:17201) UnhandledPromiseRejectionWarning: File: /Users/p/Workspace/ckeditor5/packages/ckeditor5-link/docs/assets/img/typing-before.gif tried to overwrite another file under location: /Users/p/Workspace/ckeditor5/node_modules/umberto/source/ckeditor5/16.0.0/assets/img/typing-before.gif. Try renaming the file.
(node:17201) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17201) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This comes from the fact that ckeditor5-link contains exactly the same gifs (the same file names). Before building the docs, Umberto merges files from all packages into one bundle and uses that. At this stage, a conflict appears.

**Comment by Reinmar** [comment]
I'd improve a couple of things:

* Trim the height of some of those gifs so they don't leave that much white space around (makes the text less contiguous)
* Slow down the tempo a bit.
* Make the first and last frames longer so it's easier to spot when the thing starts and ends.
* Avoid pasting text cause it's confusing (the user doesn't know how the text got there). Instead, type some short things like "Check out this code snippet:".

**Comment by panr** [comment]
@Reinmar how about now?

**Comment by Reinmar** [comment]
Better :)

I'd propose less typing next time, because that part when you're typing takes just too much time so it attracts the attention too much, but I think it's better anyway.

**Pull request merged**
